-- MySQL Script generated by MySQL Workbench
-- Mon Mar 20 13:37:06 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BandaSolApp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Componente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Componente` (
  `idComponente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `anteriorFormacion` VARCHAR(45) NULL,
  `cP` INT NULL,
  `direccion` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `fechaBaja` DATE NULL,
  `fechaIngreso` DATE NOT NULL,
  `fechaNacimiento` DATE NULL,
  `hermandad` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NULL,
  `mote` VARCHAR(45) NULL,
  `movil` INT NULL,
  `nif` VARCHAR(45) NOT NULL,
  `observaciones` VARCHAR(500) NULL,
  `profesion` VARCHAR(45) NULL,
  `telefonoFijo` INT NULL,
  PRIMARY KEY (`idComponente`),
  UNIQUE INDEX `idComponente_UNIQUE` (`idComponente` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `lugar` VARCHAR(45) NULL,
  PRIMARY KEY (`idEvento`),
  UNIQUE INDEX `idEvento_UNIQUE` (`idEvento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Componente_Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Componente_Evento` (
  `idComponente_Evento` INT NOT NULL AUTO_INCREMENT,
  `idComponente` INT NULL,
  `idEvento` INT NULL,
  PRIMARY KEY (`idComponente_Evento`),
  INDEX `fk_id_componente_idx` (`idComponente` ASC),
  INDEX `fk_id_evento_idx` (`idEvento` ASC),
  CONSTRAINT `fk_id_componente`
    FOREIGN KEY (`idComponente`)
    REFERENCES `Componente` (`idComponente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_evento`
    FOREIGN KEY (`idEvento`)
    REFERENCES `Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Instrumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Instrumento` (
  `idInstrumento` INT NOT NULL AUTO_INCREMENT,
  `numeroRegistro` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `Componente_idComponente` INT NOT NULL,
  PRIMARY KEY (`idInstrumento`),
  INDEX `fk_Instrumento_Componente1_idx` (`Componente_idComponente` ASC),
  CONSTRAINT `fk_Instrumento_Componente1`
    FOREIGN KEY (`Componente_idComponente`)
    REFERENCES `Componente` (`idComponente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Noticia` (
  `idNoticia` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `cuerpo` VARCHAR(2000) NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`idNoticia`),
  UNIQUE INDEX `idNoticia_UNIQUE` (`idNoticia` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Marcha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Marcha` (
  `idMarcha` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `autor` VARCHAR(45) NULL,
  `Componente_idComponente` INT NOT NULL,
  PRIMARY KEY (`idMarcha`),
  UNIQUE INDEX `idMarcha_UNIQUE` (`idMarcha` ASC),
  INDEX `fk_Marcha_Componente1_idx` (`Componente_idComponente` ASC),
  CONSTRAINT `fk_Marcha_Componente1`
    FOREIGN KEY (`Componente_idComponente`)
    REFERENCES `Componente` (`idComponente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
